[package]
name = "tupa-typecheck"
version = "0.6.0-dev"
edition = "2021"

[dependencies]
thiserror = "1.0"
tupa-parser = { path = "../tupa-parser" }
tupa-lexer = { path = "../tupa-lexer" }
tupa-effects = { path = "../tupa-effects" }
