[package]
name = "tupa-codegen"
version = "0.6.0-dev"
edition = "2021"

[dependencies]
tupa-parser = { path = "../tupa-parser" }
tupa-lexer = { path = "../tupa-lexer" }
tupa-typecheck = { path = "../tupa-typecheck" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
